### ISSUE TITLE
web (html/css) enhancements 

### ISSUE THREAD

**Issue by gn0st1c** [xoseperez/espurna#1132]
**NOT AN ISSUE**

0) @xoseperez : sorry, i was quite busy with work lately and couldn't spare time for espurna.

1) Color Picker:
instead of using an external js/css (jQuery Wheel Color Picker), should we move to [input type=color](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color) ?

* this would save us space. browser compatibility is quite good (even Edge supports it and nobody uses IE anyway). even the mobile version is decent enough to use.

* doesn't work on Safari (works on tech preview safari)

2) JQuery:
if we get rid of jQuery Wheel Color Picker, then moving from JQuery to cash/zepto/umbrella won't be a big work. these will also save us space.

**Comment by xoseperez** [comment]
Actually, the Wheel Color Picker is the heaviest component right now. It is only loaded in some devices that require it but still. It looks like it does not support IE and Safari Mobile. 

The color picker is not the only component that relies on jQuery. I think step two will take some time.

**Comment by mcspr** [comment]
**iro.js** looks like reasonable replacement.
https://iro.js.org
https://iro.js.org/introduction.html#features
+it is always possible to hide it behind buildflag to save some space and fallback to simple input[type=color]

Another used component is ajax, which can be replaced by [fetch api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) or [axios lib](https://github.com/axios/axios)

**Comment by mcspr** [comment]
@xoseperez point this 1.14.0?

- there was a serious bug in irojs with ios safari, but that is fixed now (circa january)
- i have not posted about testing trunk jquery builds around january too. that were slightly less in size, but had weird bugs without jquery's sizzle engine. i think that is fixed too
- i'd add another point about webui - some kind of transpiler / packer that supports es6. htmlmin silently ignores it

**Comment by mcspr** [comment]
Closing via 808981c, fa3deeffbfa622ecd1869af2563940fb3143e94e and 84a7f6337f72b011512b3e95efe36f2d661e5065
iro.js integrated in favour of mobile experience, since old wheel picker was pretty much broken. Jquery removed completely as well. Even the stripped down jquery-4.0.0-slim was 15KiB, so it is a pretty nice change for the smallest variant. Removing datatables is pretty significant 50KiB cut. (idk if it is on par though, but I hope I have not missed the rfm69 use-case here)

Not many comments on vanilla .js vs. jquery. But, after looking at c++ code, it does not seem that wordy as it did before...

*sidenote* there's also [brotli](https://nodejs.org/api/zlib.html#zlib_zlib_createbrotlicompress_options) in the current zlib builds:
```
Image index.sensor.html.br      size: 24032 bytes
Image index.rfbridge.html.br    size: 23354 bytes
Image index.rfm69.html.br       size: 23420 bytes
Image index.small.html.br       size: 22525 bytes
Image index.lightfox.html.br    size: 22872 bytes
Image index.garland.html.br     size: 22723 bytes
Image index.light.html.br       size: 33105 bytes
Image index.curtain.html.br     size: 23492 bytes
Image index.thermostat.html.br  size: 23090 bytes
Image index.all.html.br         size: 37010 bytes
```
but, that cuts [supported browsers even more than the .js changes](https://caniuse.com/brotli)
