### ISSUE TITLE
AP and STA simultaneously

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#114]
Originally reported by: **dscoolx6 (Bitbucket: [dscoolx6](https://bitbucket.org/dscoolx6), GitHub: [dscoolx6](https://github.com/dscoolx6))**

----------------------------------------

Hi, i have two SONOFF basics configured in STA mode, but i can still see my SONOFF APs in the list of wifi APs in windows. Is this normal? I dont remember seeing this behavior in 1.5.0?

**Comment by mcspr** [comment]
Closing due to age.

Current behaviour allows user to keep being connected to the AP after changing settings, thus running STA_AP mode for a small window of time. After client disconnects, AP is destroyed.
`WIFI_FALLBACK_APMODE 0` will disable AP mode from coming up at all unless forced via some action, like terminal `wifi.ap` or button.
