### ISSUE TITLE
Question: 12-bit PWM?

### ISSUE THREAD

**Issue by GaelZorro** [xoseperez/espurna#1340]
Hello!
I'm trying to get 12-bit PWM dimming (values 0-4095) on my MagicHome LED controllers, instead of 8-bit (values 0-255)... Just so that I can use powerful LEDs, and yet not get blinded when the family gets up at night.
How would you advise to do that? 
I tried to just change the constants LIGHT_MAX_PWM values and LIGHT_MAX_VALUE to 4095, but I guess there must be more legwork involved, because it doesn't work :-)
I'm not using RGB, HSV, brightness or colorpicker.

**Comment by GaelZorro** [comment]
And thanks to you and to the contributors for your great software!

**Comment by xoseperez** [comment]
PWM engine depth is defined by LIGHT_MAX_PWM and you can set it to 4095. But internally ESPurna will still use 8-bit values so LIGHT_MAX_VALUE must stay at 255.

**Comment by Adrianotiger** [comment]
Is there a way to increase this value?
I have 4 white channels and need to correct the gamma of each channel for a linear dimmer. 255 is not really much, if you want to use a look-up table for example…

I don't know where in the code I can change it from byte to int so that it would be possible to use a bigger number.

**Comment by xoseperez** [comment]
Unfortunately, it's not that simple. There are a number of places in the code where a resolution of 8 bits is used (starting with the web UI, for instance).
