### ISSUE TITLE
REST setting not persisted after reboot

### ISSUE THREAD

**Issue by ginkage** [xoseperez/espurna#1430]
When I disable RESTful API in settings and hit "Save", my devices (H801 and MagicHome 2.0) work as I expect them to (that is, respond to "GET"), but when I restart them, GET requests don't work anymore, and the setting in the web UI is always back to "On".

I tried reading through the source code, and what I've found was: actual setting (that is, value that affects the device behavior) is only ever read from EEPROM when the _apiConfigure() is called, which is essentially only ever called when there is a "RELOAD" command or when settings are saved.
On the other hand, the web UI is initialized with exactly this variable value when there's a web socket event WS_EVT_CONNECT — that is, pretty early, and way before I ever hit the "Save" button.

This code practice (setting internal variable in something registered with espurnaRegisterReload() and using that value in something registered with wsOnSendRegister()) seems to be not just limited to the REST setting, e.g. I see the same thing in the LED module, though I can't say if it has the same issue.

My current workaround for having the setting properly saved and surviving reboot is to add a single line:
espurnaReload();
in the end of the setup() function of espurna.ino file. I'm not sure if this is a correct fix, or if it might break something else, but at least it seems to work.

**Comment by mcspr** [comment]
Looking at recent changes:
https://github.com/xoseperez/espurna/commit/7a9dfb99aa799854db3f3deb9e7718332b0965b0#diff-5c4e7687b14b951c2112b197031b541c and related issue (same as here, configure method was not called on boot)
https://github.com/xoseperez/espurna/commit/938872e9c633054dcdd4444d0b763beeec3562ee#diff-5c4e7687b14b951c2112b197031b541c made it so there is no need to call reload and it is read straight from the settings

I'd check again with `dev` build instead of `master` to verify that this works
