### ISSUE TITLE
Relay Toggle on Sonoff 4ch pro

### ISSUE THREAD

**Issue by serapis80** [xoseperez/espurna#1450]
Hello to all,
I'm writing because I'm looking for a function that I want to use in Sonoff 4ch pro device in order to simulate a diverter switch.

I already installed the last and previous version of ESPURNA firmware 1.13.3 precompiled (doesn't work with Alexa) and 1.13.2 precompiled (this version does).
I tried to check if it's possible to toggle the relay with Alexa, but seems that it not present like a function.

I want to integrate the sonoff 4ch pro device in the electrical system of my home like the picture below.
![immagine](https://user-images.githubusercontent.com/46110808/50405122-77f9aa00-07b0-11e9-84ac-aac33b1d3540.png)

One relay of the sonoff 4ch pro can be used like a diverter and the other one it's the common diverter used by finger. In this way I can use my voice from Alexa and my finger (in case of wifi or internet  is not available) in order to switch on and off the light.

The problem can appears when I "switch on" the light from the hardware diverter and I want to "switch off" the light from Alexa. In this case I say to Alexa:  "turn on the light" in order to switch off.

So, I want to say to Alexa "turn on the light" and inside the Sonoff 4ch pro, the code read the actual status of the relay and change this state (if the actual status of the relay is to 0, it will change to 1 and viceversa).

I tried to modify the code in Alexa.ino:
```
void alexaLoop() {
    alexa.handle();
    while (!_alexa_dev_changes.empty()) {
        AlexaDevChange& change = _alexa_dev_changes.front();
        DEBUG_MSG_P(PSTR("[ALEXA] Device #%u state: %s\n"), change.device_id, change.state ? "ON" : "OFF");
        bool intStatusRelay = relayStatus(change.device_id);  //#new
        relayStatus(change.device_id, !intStatusRelay);       //#Original - relayStatus(change.device_id,change.state);
        _alexa_dev_changes.pop();
    }
}
```

Up to now, the compiler doesn't show any error, and I'm able to download the compiled code into the Sonoff 4ch pro device.
For other reason (not clear for me) I can't test my code.
I can change the admin password (like the fw precompiled) and after a reboot the device is connected from my wifi. But is not possible to open the web page (in some case is present the ip adress but the port 80 is not open, in other cases the device reply to bad request).

So, at the end I want to know if my code can work or this function is already present in the precompiled version.

Best Regards

**Comment by ColinShorts** [comment]
I'm not sure about your web interface connection issues, but the circuit you describe means that you'll never know if the light is on or off because of the remote switch. I got around this problem by using a Sonoff T1 as the only real switch, and then multiple T1's as slave switches. The slaves only need live and neutral power. The thing that binds it together is mqtt grouping between the relevant switches. If you are wanting to use the built-in Alexa support, your only enable it on the master switch. If you use OpenHAB, home assistant, etc, then you'd just configure the Alexa integration from there.
I've used 8x T1's in my hallway over three floors so I'm confident enough to recommend this configuration to anyone with a similar need. There is sometimes a tiny delay from the slaves, but it's usually less time than it'd take to switch on a compact fluorescent bulb and passes the spouse/guest factor in usability.

The downside is whether or not you'll have live and neutral wires at each switch, but if you've got the wires for the remote switches already, you can just put the correct colour sleaving over the wire of your choice.

Make sure your work passes all relevent building codes, consult a qualified electrician if in doubt.
