### ISSUE TITLE
Sonoff Touch 1.13.5 upgrade holds 1.13.4

### ISSUE THREAD

**Issue by henkiejan1** [xoseperez/espurna#1655]
Hi,

Today i wanted to upgrade my Sonoff Touch from Espuruna 1.13.4 to 1.13.5. Everything looks going perfect. But after the reboot the version is just 1.13.4. I'm really sure that i use 1.13.5. I think that maybe the wrong file is named 1.13.5? Oh and btw it's on all my touches the same... Not on just 1.

Thank you for your reply! :)

**Comment by mcspr** [comment]
I think the issue is with Web OTA specifically, because of how logging worked in 1.13.4.
You can try doing it via external tools instead (without opening the device's webpage, to avoid the bug):
https://github.com/xoseperez/espurna/wiki/OTA#updating-via-http
https://github.com/xoseperez/espurna/wiki/OTA#using-espotapy
