### ISSUE TITLE
ESPurna for Sonoff RF Bridge Not compatible with Sonoff PIR Sensor

### ISSUE THREAD

**Issue by old-fogey** [xoseperez/espurna#1684]
RF Bridge variant: R2 V1,0 2017.11.23.  EFM8BB1 firmware unknown.
ESPURNA variant: SDK version 1.5.3(aec24ac9) Core version 2.3.0 Firmware name ESPURNA
Firmware version 1.13.6-dev Firmware build date 2019-04-06 08:21:44

RF bridge working with ESPURNA, neither RF_RAW_SUPPORT or RFB_DIRECT options used so that we can only expect to learn devices supported by EFM8BB1 chip.

Example device (amongst extremely limited compatible ones)  is Sonoff PIR-2 sensor which works fine for 'learn' and 'save' but ESPURNA can't publish PIR events to MQTT as the PIR sensor sends a non-constant code including coded received RF signal level, battery voltage etc

Example codes received from my PIR and learnt successfully by ESPURNA are
309801A404C4E5720E
309801A404C4E5720E
30A201A404C4E5720E
3098019A04C4E5720E
308E019A04C4E5720E
30A201A404C4E5720E
30CA01A404C4E5720E
30C001A404C4E5720E
309801A404C4E5720E

**Comment by mcspr** [comment]
This is expected behaviour.
Message structure is: Sync time (2 bytes), Low level time (2 bytes), High level time (2 bytes), Data (3 bytes)
Data E5 72 0E is constant in the output you received

Also see https://github.com/xoseperez/espurna/issues/1694
Maybe we need to cut it by default, just leaving Data bytes.
