### ISSUE TITLE
Can I connect an RS232/serial device to ESP8266 (Sonoff devices) ?

### ISSUE THREAD

**Issue by sofakng** [xoseperez/espurna#1761]
I'm using a Sonoff POW R2 and Sonoff Basic devices which are ESP8266 based.

Is it possible to use these devices as relays (which is what they are), but also connect a serial/rs232 device to them?  (i.e. I want to both control the power on/off AND use it for remotely communicating with an rs232/serial device)

**Comment by sfilinto** [comment]
Although technically you could connect a serial port, i would suggest otherwise as the Low Voltage & High Voltage is not well isolated in the sonoff devices.
See the caution note at https://github.com/xoseperez/espurna/wiki/Hardware

Secondly, i dont beleive espurna will support toggling the relay via a serial connection.

have a look at the Itead Sonoff SV which does not connect to the 220V mains. it might be what your looking for.

Btw... This question might be better posted on the gitter channel rather then as an issue ( which it is not).
