### ISSUE TITLE
Sonoff Touch T1 2CH Double click

### ISSUE THREAD

**Issue by piotruuch** [xoseperez/espurna#1884]
Welcome!
I'm just starting my adventure with ESPURNA. I am delighted with this soft. I have a Sonoff T1 2CH switch. Single clicks work and control relays. How to make a double click to run IDX in Domoticz?
Regards Peter

**Comment by mcspr** [comment]
Do you mean a completely separate action that is triggered on double-click?

ref https://github.com/xoseperez/espurna/wiki/Buttons-and-switches
afaik, domoticz needs some "virtual" index to receive state and right now we only send relay ON or OFF values. but I am not super familiar with it

Note that you would still trigger relay when pressing the button twice, because ITEAD_SONOFF_T1_2CH is configured to watch for PRESSED event. One way to solve this is to swap relay action from _PRESS to _DBLCLICK in configuration headers. ITEAD_SONOFF_T1_2CH set-up to trigger relay action on a single press and does nothing with either multi-click events (note that event number != number of presses / button state):
https://github.com/xoseperez/espurna/blob/35ce68710cc51fae2e185a6d5edff31a6d035002/code/espurna/config/hardware.h#L800-L803
i.e. PRESS == NONE, DBLCLICK == TOGGLE

Or you could disable relay action completely, but you'd need to somehow figure out a way to receive event numbers AND decipher them. Hopefully, without any internal scripting
