### ISSUE TITLE
Relay not switching from Domoticz

### ISSUE THREAD

**Issue by lamptah** [xoseperez/espurna#2034]
Running the new 1.14.0 on a SONOFF BASIC. Noticed that a) on/off commands from domoticz are not being executed despite them showing up in the DEBUG window and b) only transitions from off to on are being reported to domoticz.

Looked at which changes were implemented between functioning 1.13.5 and 1.14.0 and narrowed it down to this:

```
bool _domoticzStatus(unsigned char id) {
  //  if (id >= _dcz_relay_state.size()) return false;  
    return _dcz_relay_state[id]; 
} 

void _domoticzStatus(unsigned char id, bool status) {
  //  if (id >= _dcz_relay_state.size()) return;
    _dcz_relay_state[id] = status;
    relayStatus(id, status);
} 
```

Commenting out the two if statements above as shown makes everything work smoothly again. I am not quite sure what those are supposed to do, maybe ">" instead of ">="? With only one relay, size() and id are both 0.

**Comment by mcspr** [comment]
This is a double whammy of not properly adjusting Domoticz stuff and pushing Tuya changes after 3 months. Also noticed in the https://github.com/mcspr/espurna-nightly-builder/issues/7

You are correct that the check is completely unnecessary and does not even work because of the way vector is used. And it probably needs to be replaced with `std::bitset<RELAYS_MAX>` (and no need to resize) anyway to save a bit of code size and avoid pulling `vector<bool>` at all.
