### ISSUE TITLE
WIFI Network can't be removed

### ISSUE THREAD

**Issue by lblabr** [xoseperez/espurna#2035]
on 1.14 i tried to delete my Wifi Settings. my configured Network (1) could not be deleted.

i would like to give my plug to my neighbor, so it need to be removed...

Thanks in advance

Lars

**Comment by mcspr** [comment]
Notably, this was not broken in 1.14.0 and was a problem in 1.13.5 too.
Workaround is to not “Delete network”, but to just erase ssid and passphrase in an existing one and “Save”.
Or, use DEBUG panel and do `del ssid0` and `del pass0` (note of the index. you can check all keys with `keys` or each key with `get ssid0` etc.)

When saving the data it never sends any “ssid” or “pass” arrays, thus settings backend never knows that we want those gone. Will be fixed by the https://github.com/xoseperez/espurna/pull/1986, so please don’t close this yet.

**Comment by lblabr** [comment]
okay, thanks!
