### ISSUE TITLE
NTP returns date in 2036

### ISSUE THREAD

**Issue by flucasro** [xoseperez/espurna#2083]
The NTP library returns many times a date in 2036. It can stay hours in my case until a valid resync happens.
I propose to make a condition to treat this magic number from the output of the NTP library, discard it, and do not set the NTP Synced flag in the espurna wrapper. I have not investigated enough on what number is it.

**Comment by mcspr** [comment]
See #1380 and my forked lib. There general issue is that the timestamp is 0 and we try to substract timezone offset from 0, overflowing the unsigned integer causing the timestamp to be in 2036.

I need to look again at the built-in client though, I don't remember if there the safeguards against bad data are enabled. If not, that'll require a patch to the upstream config so that lwip is built with those enabled.
And you may want to use a different ntp server.
