### ISSUE TITLE
RGB | mqtt | values = channel * brightness

### ISSUE THREAD

**Issue by lblabr** [xoseperez/espurna#2087]
i read [2033](https://github.com/xoseperez/espurna/issues/2033)

today i cloned latest dev version, an it seems that in mqtt messages for each rgb channel, still the channel value is multplied by brightness

could somebody confirm that ?

![image](https://user-images.githubusercontent.com/5998943/71559429-14a6f580-2a5e-11ea-9c95-f57ddd0bc7f3.png)

**Comment by mcspr** [comment]
The underlying issue was with the groups. Because group topic only sent converted values, those were incorrectly parsed by the receiving side when brightness was different between devices. Values always decreased when brightness was less than 255, eventually dimming all grouped lights. 
From HA side you do already know the brightness value to convert back? For example, in case of Home Assistant, it accepts both payloads and takes brightness into an account
