### ISSUE TITLE
MQTT | {hostname}/rgb/set

### ISSUE THREAD

**Issue by lblabr** [xoseperez/espurna#2089]
espurna: latest dev

set RGB with mqtt does not work: {hostname}/rgb/set

setting channel works
{hostname}/channel/0/set

![image](https://user-images.githubusercontent.com/5998943/71561172-3c548880-2a73-11ea-82ba-dd70e4292c97.png)

**Comment by mcspr** [comment]
Just as I wanted to say about reconnecting MQTT... While this looks like user error, it is still confusing that settings don't actually do anything before some other manual action.

One solution is to issue subscription when useColor or useCCT change from OFF to ON:
https://github.com/xoseperez/espurna/compare/dev...mcspr:lights/mqtt-resubscribe
https://github.com/xoseperez/espurna/compare/dev...mcspr:lights/mqtt-resubscribe?expand=1#diff-1e2d5ef62603513c39da08ec25f60755R1341-R1345
But something like Home Assistant would also need a refresh, since autodiscovery sends out only on connection too. So maybe a full reconnection would also work, MQTT module even has a small helper method for that.
