### ISSUE TITLE
mqtt rever reconnects

### ISSUE THREAD

**Issue by ghost** [xoseperez/espurna#2112]
using 1.14.1 mqtt is disconnected and never reconnects.

mqtt.reset and wifi.reset do not help

mqtt.info is always in "connecting status"
[547326] [MQTT] Client ENABLED, DISCONNECTED
[547326] [MQTT] Retry CONNECTING (Now 461547326, Last 132664642, Delay 5000, Step 5000)
[547332] +OK

After a fast inspection to the code it seems that in mqtt.ino _mqtt_connecting is set to true,
and the event _mqttOnConnect() is never received.

Or this is treated as a bug in ASYNCMQTTCLIENT, or there is need of a workaround with a timeout after connect request to force a mqttDisconnect()?

**Comment by mcspr** [comment]
See https://github.com/marvinroger/async-mqtt-client/pull/156
If remote drops off the network for some reason, MQTT client will reconnect only after 15 minutes (internal TCP retry timeout)

I'd ping the PR there first, then we can think of adding it locally as forked version

**Comment by ghost** [comment]
Please see the log message
[739066] [MQTT] Retry CONNECTING (Now 513739066, Last 33600056, Delay 5000, Step 5000)

the "now", and "last" values... I think that there is something more to the 15min and the half open connections. NTP is syncing and RSSI is -65

**Comment by mcspr** [comment]
But when does this happen? How to reproduce the issue?
Did broker disappear from the network temporarily / abruptly shutdown / IP address changed?

Log only says that neither connection or disconnection routine ever completed, not the reason why it is waiting. Looking at async-mqtt-client again, it never sets data-receive timeout for connection loop. If I load netcat listener on port 1883, it will never complete connection routine. see `netstat` command. Only after shutting down the 1883 listener it will cleanly break the connection, restoring the loop.

To avoid doing that: mcspr/async-mqtt-client@c1fcfd1
This will impose 10 second window to finish the connection after CONNECT packet is sent, since ping keepalive does not yet work.
Value is hard-coded tough, maybe it can be the same as keepalive?

I also noticed marvinroger/async-mqtt-client@7f1ba481a22d56ccf123e4b2f6e555d134c956d0 in the latest version, but we don't call those methods from mqtt callbacks.
