### ISSUE TITLE
S20: After flashing ESP Core 2.6.3, cannot flash espurna-itead-s20

### ISSUE THREAD

**Issue by nstrelow** [xoseperez/espurna#2168]
**Problem**
Sonoff S20->flashed espurna -> SoftAP is not firing up, no leds are blinking

Probable cause: Some incompatible SDK config I cannot seem to reset

Working
* Arduino sketch with ESP Core 2.6.3
* nodemcu-lolin-latest (prebuilt, working great ) 

Broken
* itead-sonoff-s20 (prebuilt)
* espurna-core (prebuilt)
* Arduino sketch with ESP Core 2.3.0

**Additional Details**
* erases and flashes fine without error
* only garbage on Serial Monitor (tried all baud rates)
* also plugged it into wall socket*

EDITS: Adapt after better understanding the problem

**Comment by mcspr** [comment]
Couple of things to note:
-  "Uploading an arduino sketch" means latest Core release 2.6.3? It installs different sdk, might cause problems without full flash erase / choosing option to erase SDK settings. .bin files use 2.3.0, but you can also try `nodemcu-lolin-latest.bin` that builds with recent version (nothing really different between s20 and nodemcu binaries, only default cfg. note that you will need to flash next .bin wired too, OTA will break because of different flash layout settings)
- "tried all baud rates"
115200 is the default rate for us. 74880 should show bootloader messages.
- "DOUT" was kind of my first though, but flash erase would've fixed that.

**Comment by nstrelow** [comment]
* Yes, Core release 2.6.3. Good to know that it might cause problems.
* Will try nodemcu-lolin-latest.bin

Immediately after flashing + buidling via PlatformIO I got this in 115200:
```
Fatal exception (0): 
epc1=0x402357cc, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
```
When I replug it, Serial prints garbage again.

Any way of resetting the SDK settings for sure?

**Comment by nstrelow** [comment]
@mcspr You are a hero!
`nodemcu-lolin-latest.bin` works!
I can press the button to turn the switch on and off. Also SoftAP is there.

Flashing itead-s20 afterwards, I again get the error.

Tried to use the Serial commands:
- factory.reset
- erase.config

**Comment by nstrelow** [comment]
More info:
Downgraded to ESP Core 2.3.0 and flashed an Arduino sketch.
SAME problem, same garbage on Serial.
Seems like my ESP is now only compatible with ESP Core 2.6.3. builds.

Any way to remove this incompatibility? Tried all kinds of ESP.eraseConfig() but nothing seems to make it work with the s20 prebuilt binary of espurna.

**Comment by mcspr** [comment]
> Any way to remove this incompatibility? Tried all kinds of ESP.eraseConfig() but nothing seems to make it work with the s20 prebuilt binary of espurna.

`esptool.py write_flash --erase-all` or `esptool.py erase_flash` + `write_flash` does not work? Doing eraseConfig work before it is even needed.

btw Core version is configurable through the `platform = ...` setting in the platformio.ini, either in global `[env]` or in `[env:...]`.

**Comment by nstrelow** [comment]
I tried `esptool.py erase_flash + write_flash` multiple times, same error.

> btw Core version is configurable through the platform = ... setting in the platformio.ini, either in global [env] or in [env:...].

good to know, so I could build my own with a newer version.

But right now, `nodemcu-lolin-latest` is able to do everything I need.
