### ISSUE TITLE
RF Bridge Direct Mode Hack Instructions

### ISSUE THREAD

**Issue by mattster98** [xoseperez/espurna#2252]
Regarding:
https://github.com/xoseperez/espurna/wiki/Hardware-Itead-Sonoff-RF-Bridge---Direct-Hack

I followed these instructions on my R2 v1.0 Sonoff RF Bridge and had some weird results.

Most importantly, when it was powered on, it was constantly transmitting on the 433MHz frequency..  I couldn't find any others who had run into this, but probably few others have equipment to otherwise hear the signal.  It would send commands that I could also hear on the carrier, but the carrier never went away, which is bad & wrong.

In any case, I reverted the hack and re-flashed with the non-direct firmware and all is well now, so I'm guesssing it was something with the transmitter side of the connection.  I used 220 Ohm resistors and checked my connections and cut traces probably a dozen times over the course of trying to make this work properly.  Perhaps something was pulled up instead of down in the normal state or vice versa?

If anyone has had success, or similar results to me, I'd love to discuss.  I'd like to make sure any corner cases are updated or at least mentioned in the wiki for troubleshooting purposes.

Thanks!

**Comment by alceasan** [comment]
I have the same issue, and it's a real problem because it completely blocks other 433Mhz signals to the point my garage door RF opened doesn't work (nor the nearest neighbors).

The solution I have is shutting down a few seconds and up again every time I send a signal with it. I have an automation on Home Assistant to do this, I first tried to reboot it, but it only stops when cutting power. You'll also need a smart switch, but you can do it with a cheap S20.
