### ISSUE TITLE
New Gosund Sp112

### ISSUE THREAD

**Issue by wildewuzz** [xoseperez/espurna#2350]
I've got some older SP112 ... they are working fine with the BWSHP5

Yesterday i received 4 new SP112 from Amazon ... build in Poland ( on the Backside )

I can switch the 230V from the Browser and via MQTT but

1. The Button on Top is not working
2. The Powermeter is not working
3. The USB Power is not switchable and OFF

...... somebody else with the probs ?`

Chris

**Comment by mcspr** [comment]
I believe it's this one?
https://templates.blakadder.com/gosund_SP112_v3_4.html

https://github.com/xoseperez/espurna/issues/1998 mentioned at least 2 different revisions
We should support power sensor after swapping CF1 and CF pins in the config / runtime (ref.  https://github.com/xoseperez/espurna/issues/2206#issuecomment-619485063, runtime settings are `hlw8012CFGPIO`, `hlw8012CF1GPIO` settings / [these build flags](https://github.com/xoseperez/espurna/blob/21e9477d9645c4cf94ade49ac5f6dd268b2b6f81/code/espurna/config/hardware.h#L3185-L3186))

[Buttons](https://github.com/xoseperez/espurna/blob/21e9477d9645c4cf94ade49ac5f6dd268b2b6f81/code/espurna/button.cpp#L726) and [LEDs](https://github.com/xoseperez/espurna/blob/21e9477d9645c4cf94ade49ac5f6dd268b2b6f81/code/espurna/led.cpp#L464
) are similarly configurable via settings (not via nice UI, though, yet, and not yet any relay GPIO because of some backlog issues)

Would you be able to adapt SHP_V23 config and try out building for this SP112_V34?
