### ISSUE TITLE
Build for Shelly25

### ISSUE THREAD

**Issue by evelinamp** [xoseperez/espurna#2385]
Hello everyone and I am sorry for this simple question. I am very new to hardware and firmwares. I am trying to build espurna-1.14.1 for shelly25. I have tried some different configuration but it doesn't work. I do not know exactly what to change and where. Can someone tell me what a simple configuration would be in order to build the firmware correctly? Thanks a lot.

**Comment by mcspr** [comment]
...not when you have not described what you tried so far!:)

You should be able to build by using either:
- `pio run -e allterco-shelly25`
- `env ESPURNA_FLAGS="-DALLTERCO_SHELLY25" pio run -e esp8266-2m-base` (in case you want some additional build flags present)

Check out:
- https://github.com/xoseperez/espurna/wiki/PlatformIO
- https://github.com/xoseperez/espurna/blob/dev/code/espurna/config/general.h flags & comments
- https://github.com/xoseperez/espurna/blob/dev/code/espurna/config/hardware.h comments & devices
- https://github.com/xoseperez/espurna/blob/dev/code/platformio.ini comments
- https://github.com/xoseperez/espurna/blob/dev/code/platformio_override.ini.example comments
(note that build process is only documented for the development version, since it began to differ too much to maintain both at the same time)
