### ISSUE TITLE
Use DHCP for DNS and/or Change DNS via GUI

### ISSUE THREAD

**Issue by techfixpros** [xoseperez/espurna#2389]
**Is your feature request related to a problem? Please describe.**
*Alternate DNS is set to 8.8.8.8 by default, with no option to change it via GUI. Alternate DNS also does not follow DHCP-supplied value. "Softcoded" DNS lookup sources can bypass LAN security policies if extra steps are not taken to lock down network.*

**Describe the solution you'd like**
*Provide a GUI interface to change DNS, and/or use DHCP-supplied value instead of 8.8.8.8. Or simply remove the "softcoded" "dns0" configuration.*

**Describe alternatives you've considered**
*Taking a backup, modifying "dns0": to desired value, and restoring from modified backup allows changing value.
Although Espurna device can resolve local hostnames properly, there is no need for a secondary "softcoded" value, i.e. 8.8.8.8. I am using PiHole and have created firewall rules to block DNS requests from (v)LAN sources to everything other than local PiHole.*

**Comment by mcspr** [comment]
What version are you using?
https://github.com/xoseperez/espurna/search?q=8.8.8.8 yields no results, I believe I removed them from both default settings and WebUI some time ago and even 1.14.1 includes this change:
8e7854b04e3d6dfef22b29444218b08dc7425b92
However, you may have gotten it into settings from previous releases, since old WebUI included text-input default value and may have saved it 

Note that unless you are using static IP setting, gateway and dns settings are ignored in favour of dhcp client configuration

**Comment by techfixpros** [comment]
I am on 1.14.1 on all modules, but they were initially running a previous version and were upgraded and restored with backups from previous versions. This can be closed as they retained that value from previous builds. Thank you.
