### ISSUE TITLE
Set default datetime on boot (use case without NTP)

### ISSUE THREAD

**Issue by itarika2** [xoseperez/espurna#2421]
In real life I use different firmware for esp8266 devices, all of them in local network only. So, I usually don't need NTP at all. But without time setting, devices goes to reboot every ±15 min.

My use case (for example in Tasmota) is one simple rule on every boot: set default datetime.

How to do this in espurna?

**Thanks!**

**Comment by mcspr** [comment]
You mean with `NTP_SUPPORT` flag set to 0 it still tries to do... something with the time?

Scheduler is also ON implicitly, needs to be off as well since it only works via the clock time
https://github.com/xoseperez/espurna/blob/660493a1db47a4248f5cd34ebff584a9c1b126cc/code/espurna/config/general.h#L1602
https://github.com/xoseperez/espurna/blob/660493a1db47a4248f5cd34ebff584a9c1b126cc/code/espurna/config/general.h#L1566

**Comment by itarika2** [comment]
@mcspr Yes, all these features are disabled, but the regular reboots still continues...

**Comment by mcspr** [comment]
But how datetime is supposed to workaround that? 

We do still run DHCP <-> SNTP service under the hood. You can disable the SNTP service before it starts though,
inserting `sntp_servermode_dhcp(0);` somewhere in `setup()` func
https://github.com/xoseperez/espurna/blob/660493a1db47a4248f5cd34ebff584a9c1b126cc/code/espurna/main.cpp#L332

If reboot is caused by some kind of crash you should be able to see it via serial (when it happens) or via `crash` (or `crash force` if you already seen it) command after the fact, and decode the resulting trace via
https://github.com/me-no-dev/EspExceptionDecoder

**Comment by itarika2** [comment]
@mcspr great, it works! Uptime - 48h without reboots and crashes.
Thank you!

**Comment by mcspr** [comment]
Any chance you could decode the crash? I don't think it is something intended by the SDK :)
Note that you need the same .elf file used to generate the .bin you are running, otherwise stack-crash addresses are almost random throughout the app
