### ISSUE TITLE
SonOff RF Bridge 433 Number of Switches

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#262]
Originally reported by: **Werner (Bitbucket: [SonOff](https://bitbucket.org/SonOff), GitHub: [SonOff](https://github.com/SonOff))**

----------------------------------------

Hello,
I have a little bit experience with tasmota and i'm able to compile a binarie for flashing.
But i'm not able to compile Espurna . I tried this with platformio  and arduino without success .

I want change the numbers of Switches from default 6 to 10 switches .
I can change the dummy switches but cannot compile the firmware.

Who can help me and can provide a binarie ?

It would be nice when we can change the number of switches in Espurna -Settings like adding Wifi-Networks !!!

**Comment by xoseperez** [comment]
@SonOff I can't reproduce this. Can you provide more information? Does it always happen?

**Comment by sonoff** [comment]
Hi Xose

I very find this file: espurna-1.11.2-itead-s20.bin and espurna-1.11.2-itead-th160.bin

Can you help me?


Feladó: Xose Pérez <notifications@github.com>
Válasz címzettje: xoseperez/espurna <reply@reply.github.com>
Dátum: 2018. február 3., szombat 22:22
Címzett: xoseperez/espurna <espurna@noreply.github.com>
Másolatot kap: Dénes Zoltán <zoli@deneszoltan.hu>, Mention <mention@noreply.github.com>
Tárgy: Re: [xoseperez/espurna] SonOff RF Bridge 433 Number of Switches (#262)


@sonoff<https://github.com/sonoff> I can't reproduce this. Can you provide more information? Does it always happen?

**Comment by xoseperez** [comment]
Sorry, I thought we were talking about the RFBridge, those images are meant for other devices. I have tested the firmware with 10 switches and domoticz integration with no problem. I can switch them all on/off with the remote, with ESPurna via the web UI or with domoticz...

**Comment by cracautanu** [comment]
I made it work with 18 devices. IT's not fully tested but seems fine. I tried more than 18 and the admin console is not accessible anymore.
https://drive.google.com/open?id=1-MqI5Wa0p6iFetlhXRNLpeM3RnK4124B

@xoseperez - Thank you for sharing your great work! A small request if possible: WEB_REMOTE_DOMAIN should be configurable from the web interface. For me - the http api option was useless without setting cors domain so I had to recompile the release. The problem is that I will have to change again the domain when finishing my web client development and this is a bit time consuming...

**Comment by tomburke74** [comment]
Great work guys firstly! I'm trying to get more than the 8 switches working in 1.13.3, I tried the above 18 device build from @cracautanu , the device flashes ok and the 18 switches appear but won't learn, am I doing something wrong? Thanks

**Comment by xoseperez** [comment]
There have been quite a few changes in the RFBridge and relay codes in the latest 2 months. I can run the firmware with 24 devices. Still, I'm doing some changes to make it more reliable.

**Comment by xoseperez** [comment]
Staged for release

**Comment by tomburke74** [comment]
Hi, would you have a compiled version that supports 24 devices I could try?

**Comment by ColinShorts** [comment]
@mcspr builds and releases nightly dev builds [here](https://github.com/mcspr/espurna-nightly-builder/releases), if you don't want to build your own.

I've not tried it yet, but I'm getting to the point that I'll need to 😀

**Comment by ColinShorts** [comment]
Actually, I just tried Max's binaries, and they're still set to use 8 switches, so you still need to change DUMMY_RELAY_COUNT to 24 and compile it.

I've done that, and attached a binary for you to test - it works ok for me, but I've only added a device at switch 8 and 9. 

The binary will need to be uncompressed first (gunzip or 7zip, etc):
[itead-sonoff-rfbridge-24.bin.gz](https://github.com/xoseperez/espurna/files/2799997/itead-sonoff-rfbridge-24.bin.gz)

Maybe @xoseperez might consider upping the default number of devices before pushing the next master?

**Comment by tomburke74** [comment]
Thanks for that, much appreciated, it updates ok and the 24 switches do appear with the previous populated 0 - 8 codes, however adding more codes results in mine resetting and wiping everything, i've attempted it on two rfbridges.

**Comment by mcspr** [comment]
@tomburke74 you can also just use a single bridge, subscribe to the `<root>/rfin` topic and compare the codes there (for input 2F4401A404BA**EA2628** use the bold part for comparison)

I juust tried 24-switch build.
After adding 36 codes (18 switch ON OFF pairs) it starts hitting the eeprom storage limits.
Not seeing any resets though, both mqtt + homeassistant discovery enabled.
```
keys
[340567] Number of keys: 216
[340569] Current EEPROM sector: 251
[340572] Free EEPROM: 10 bytes (0%)
[340575] +OK
```
```
eeprom.dump
         00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
------------------------------------------------------
0x0000:  00 12 00 0E 19 00 00 00 00 00 03 37 48 71 7A 70            7Hqzp
0x0010:  09 80 00 00 01 00 01 00 00 32 46 34 34 30 31 41          2F4401A
0x0020:  34 30 34 42 41 45 41 32 36 32 38 00 12 72 66 62 404BAEA2628  rfb
0x0030:  4F 4E 31 38 00 07 32 46 34 34 30 31 41 34 30 34 ON18  2F4401A404
0x0040:  42 41 45 41 32 36 32 37 00 12 72 66 62 4F 46 46 BAEA2627  rfbOFF
0x0050:  31 37 00 08 32 46 34 34 30 31 41 34 30 34 42 41 17  2F4401A404BA
```

I'd use a separate issue for this, EEPROM size limits being the main one. Easiest fix rn is to avoid creating default keys for relayTimeN, relayPulseN, tspkRelayN etc. when they can be sourced from the code instead. Next on the docket is to fix web sending them, as it turns out the change detection is not fully working (will extract from #1387)
