### ISSUE TITLE
Ability to have multiple but same type sensors

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#354]
Originally reported by: **blue (Bitbucket: [bluexp](https://bitbucket.org/bluexp), GitHub: [bluexp](https://github.com/bluexp))**

----------------------------------------

Trying latest version today I found out that I can have only one of ds1820 or dht sensors working at a time.
I suggest implementing the ability to monitor both of those sensor simultaneously.
And  I also suggest adding a feature to the software to define more than one sensor of the same type, i.e defining 2 ds1829 and 3 dht ,etc

**Comment by MiG-41** [comment]
> . You can connect multiple sensors to the same GPIO and it will detect and use all of them...

I have a lot of chinesse DS18B20 under the floor , but the problem is ,that they have to be max 5Pcs on one bus/GPIO . More of them couses no detection , and stronger pullup helps only partially ( you can add 1Pcs more ). 
So Looking for opportunity ,where it is possible to use more then one GPIO in ESP8266... It will work ?
