### ISSUE TITLE
Can't update OTA

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#441]
Originally reported by: **Ingo Heinicke (Bitbucket: [skyynet](https://bitbucket.org/skyynet), GitHub: [skyynet](https://github.com/skyynet))**

----------------------------------------

After flashing 1.12.0 I wanted to upgrade the first time OTA. My Sonoff Dual R1 shows up in Arduino IDE but when I want to upload it I get a board password requester. When I enter the login pw for web interface it doesn't work.

Then I wanted to upload the compiled espurna.ino.bin file via ESPurna web interface. There I get an error message "There was an error trying to upload the new image, please try again (ERROR 4)". My binary is smaller than 500kB (this caused an error some time ago so I mention it).

**Comment by xoseperez** [comment]
@skyynet Any update on this?

**Comment by skyynet** [comment]
Just tried to locate "/portable/packages/esp8266/hardware/esp8266/2.3.0/boards.txt" on my Mac but didn't succeed. I assume it's part of the Arduino IDE? Checked the Arduino folder in my User's home folder but couldn't find it.

**Comment by xoseperez** [comment]
The exact path does not have to be necessarily the same. In particular, if you have a standard installation the "portable" folder might not exist. Just look for a "hardware" folder under your Arduino folder installation and browse from there.

**Comment by skyynet** [comment]
Ah, I finally found it. It's located within the user's Library folder -> Arduino15 -> packages -> esp8266 -> hardware -> esp8266 -> **2.4.0** -> boards.txt

Since I already use 2.4.0 there was no need to add anything. I was able to select 1M (no SPIFFS) under Flash Size in Arduino IDE. After recompiling the sketch and updating via USB I am now able to update via WiFi. Thanks for the hints.
