### ISSUE TITLE
Not all led modes in WebUI

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#458]
Originally reported by: **Maxim Prokhorov (Bitbucket: [jhdtl](https://bitbucket.org/jhdtl), GitHub: [jhdtl](https://github.com/jhdtl))**

----------------------------------------

Looks like General/LED Mode setting is missing `LED_MODE_FOLLOW`(2) and 
`LED_MODE_FOLLOW_INVERSE`(3) from the config/general.h

I'm using this with couple of basic sonoffs. Setting ledMode0 to 2 or 3 manually though terminal/telnet causes the select element to become blank. Next time **Save** from web sets ledMode0 to (null)

**Comment by xoseperez** [comment]
Those two modes are there for future reference. The problem is that right now the code is only managing the first LED for notifications, so the available modes refer to "global" status, not per LED or per relay. 

LED_MODE_FOLLOW is equivalent to LED_MODE_FINDME but the later takes all relays into consideration.

This is something that will eventually be implemented with version 2, since the goal is to be able to configure basic hardware from the web UI, including the LEDs.

**Comment by mcspr** [comment]
I see. But if i am reading this right FINDME is actually more like FOLLOW_INVERSE, only for the first relay.
Maybe FINDME_INVERSE makes sense right now? Instead of two FOLLOW and FOLLOW_INVERSE. At least web would not break like this:

![default](https://user-images.githubusercontent.com/132763/35391216-1577c06e-01ef-11e8-8309-2c5abae40bac.png)
1. from web, set led to mqtt managed 0
2. go to web inspector and swap select values to 2 / set ledMode0 2
3. save, ledMode0 now 2
4. refresh, save. ledMode0 now null.
![default](https://user-images.githubusercontent.com/132763/35391463-d197dffe-01ef-11e8-9449-e7aee871a9cd.png)
5. rebooting keeps it set to null, led does not work until save is issued again from web so the default value or 0 is picked up again from select element.

**Comment by xoseperez** [comment]
Yes, my bad. FINDME is FOLLOW_INVERSE. The idea is that you want the LED on when the switch is off to find it in the dark.

Maybe you could explain why do you need the FINDME_INVERSE mode (so the LED on when any/all switches are on).

**Comment by mcspr** [comment]
As I said - Sonoff Basic. It does not have any indication as POW, or Touch models. I have it screwed to the multi outlet, infrequently powered.

**Comment by xoseperez** [comment]
And you want a visual notification when the relay is on? Have you tried the "mixed mode"?

**Comment by mcspr** [comment]
Yeah. POW turns on blue led when relay switches on, T1 shows each relay via button led. I just felt like this was most sensible setting when the power outlet is visible most of the time with relay off.

**Comment by xoseperez** [comment]
I have added the LED_MODE_STATUS that's exactly the opposite the LED_MODE_FINDME. It's in the dev branch now.

**Comment by xoseperez** [comment]
Will be released with 1.12.2

**Comment by mcspr** [comment]
Changed all of basics to dev branch with Status mode enabled. Looks great. Thanks!

**Comment by xoseperez** [comment]
Cool. Will be released soon.
