### ISSUE TITLE
Send IR commands via MQTT

### ISSUE THREAD

**Issue by JumpmanJunior** [xoseperez/espurna#556]
I use espurna on a MagicHome LED controller which also has a IR remote. When I turn on the LEDs or switch the colour with the remote the new state of the LEDs is send via MQTT to the MQTT broker. It would be nice if also the button press on the remote would be send via MQTT. There are various buttons on the remote which do not work in espruna (yet?) - like "flash" or "strobe". If the information that one of these buttons was pressed would also be send via MQTT I would be able to control further things with this remote.

**Comment by izharm** [comment]
Hi,
I have tested this feature in version 1.13.3a and found a few issues:

1. Raw Rx doesn't work, _irRXLoop() fails on "check code" and returns. I was able to get it to work by moving the checks :

        // Check code
        if (_ir_results.value < 1) return;
        if (_ir_results.decode_type < 1) return;
        if (_ir_results.bits < 1) return;

to the none ir_use_raw section.

I didn't test this with the non raw option though.

2. IR Tx MQTT messages were split on reception and the IR send code wasn't working well.  It seems this is due to TCP buffer size, as described here [https://github.com/marvinroger/async-mqtt-client/issues/98#issuecomment-379969767](url), so changing the lwIP (lightweight IP) option to "V2 higher bandwidth" solved this issue.

I am now able to receive and send raw IR message.

By the way, the code mentions to "increase MQTT packet size -DMQTT_MAX_PACKET_SIZE=1200" - As far as I can tell, this doesn't work when using MQTT_USE_ASYNC, maybe you need to add _mqtt.setMaxTopicLength in _mqttConnect().  I didn't see a difference and the code worked either way (once the TCP issue was resolved) 

thanks for your continuing efforts.

Izhar
