### ISSUE TITLE
Compile error with AsyncStaticWebHandler sonoff-debug

### ISSUE THREAD

**Issue by xoseperez** [xoseperez/espurna#6]
Originally reported by: **an_indian_man (Bitbucket: [an_indian_man](https://bitbucket.org/an_indian_man), GitHub: Unknown)**

----------------------------------------

pio run -e sonoff-debug
Win10 x64
platformIO
ESP-stage

.piolibdeps\ESPAsyncWebServer_ID306\src\WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified(tm*)':
.piolibdeps\ESPAsyncWebServer_ID306\src\WebHandlers.cpp:67:64: error: 'strftime' was not declared in this scope
strftime (result,30,"%a, %d %b %Y %H:%M:%S %Z", last_modified);
^
.piolibdeps\ESPAsyncWebServer_ID306\src\WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified(time_t)':
.piolibdeps\ESPAsyncWebServer_ID306\src\WebHandlers.cpp:72:60: error: 'gmtime' was not declared in this scope
return setLastModified((struct tm *)gmtime(&last_modified));
^
.piolibdeps\ESPAsyncWebServer_ID306\src\WebHandlers.cpp: In member function 'AsyncStaticWebHandler& AsyncStaticWebHandler::setLastModified()':
.piolibdeps\ESPAsyncWebServer_ID306\src\WebHandlers.cpp:77:25: error: 'time' was not declared in this scope
if(time(&last_modified) == 0) //time is not yet set

**Comment by igrowing** [comment]
This compilation problem happens in Windows only. Linux and Mac are case sensitive for files, so these OSes differ between `time.h` and `Time.h`. Windows doesn't.
The problem comes when `Time_ID44` lib in installed (that's often used lib) and `ESPAsyncWebServer_ID306` lib includes `time.h` in `WebHandlerImpl.h`.
So wrong time lib is included due to OS case insensitivity.
There is advice to include `TimeLib.h` instead of `time.h`. Tried this, doesn't work.
Workaround that works:
1. Rename the lib:
- Go to: <drive>:\Users\<username>\.platformio\packages\toolchain-xtensa\xtensa-lx106-elf\include
- Rename `time.h` to `_time.h`.
2. Find all occurrences of `WebHandlerImpl.h` in your Windows.  Replace `#include <time.h>` with `#include <_time.h>`
3. Build your project. (Recommended restart platformio before the build).
