### ISSUE TITLE
Blank webpage in firefox when connecting from different network/subnet 

### ISSUE THREAD

**Issue by l3d00m** [xoseperez/espurna#813]
I am having a problem similiar to #667 with firefox, but only if I connect from a different network / subnet. The web page does render without problems if I'm in the same network as the sonoff bridge (192.168.110.0/24) . But if I'm in a different network (e.g. 192.168.100.0/24) which has a route to the first network, it just displays the blank page and "ESPurna 0.0.0" as the title with the following console output:

```
Firefox can’t establish a connection to the server at ws://192.168.110.51/ws. 192.168.110.51:3:18172
```

Because the error message is pretty different to #667 I decided to open a new issue. 

Using Firefox 59.0.2 (64-bit) (happening on Ubuntu and Windows 10)

**Comment by ColinShorts** [comment]
Did you try shift-reloading? I see the same thing from time-to-time, and I don't think it's limited to FireFox (running in Ubuntu), I'm sure I've seen the same behaviour on Chrome on Android.

**Comment by xoseperez** [comment]
Does it work when using another browser? Is there any other JS error (even on another browser)?

**Comment by wildwiz** [comment]
On my maxbook I can reproduce the issue in this way:
a) enter into the web page of the device
b) reconnect
The page title then says Espurna 0.0.0 with blank page
What I noticed is that rather than trying to connect the websocket with url 'ws' the page gets a 404 from 'menuws'. Also, the 404 arrives with some delay, like some timeout has passed.
Reloading fails
If I remove the #menu at the end of the URL, the page works again.
Seems that the #menu fragment interpheres somehow with the generation of the websocket url ?

**Comment by wildwiz** [comment]
Update: trying to reproduce against a DEV build 1.12.6a current to github repo seems to work properly. Seems that the offending line was line 1306 in function connect in https://github.com/xoseperez/espurna/blob/master/code/html/custom.js. On dev version the function has been overhauled and seems to close the bug.

**Comment by xoseperez** [comment]
1.12.6 has just been released. Can you tested it against master branch?

**Comment by l3d00m** [comment]
I'll need a few weeks, sorry for that. Thanks for the fast reponse though!

**Comment by wildwiz** [comment]
With 1.12.6 I can no longer reproduce the issue, looks that was it !

**Comment by xoseperez** [comment]
Great. Closing. Thanks for your feedback.
